#!/bin/bash
# =============================================================================
# Server Setup Script for UP Schedule Generator
# =============================================================================
# This script prepares a fresh Ubuntu server for production deployment:
# - Installs Docker and Docker Compose
# - Configures UFW firewall
# - Hardens SSH configuration
# - Sets up fail2ban for brute-force protection
# - Configures Docker Hub authentication
# - Pulls and starts containers
# - Sets up auto-restart on boot
#
# Usage: sudo bash server-setup.sh
# Requirements: Ubuntu 20.04+ or Debian 11+
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APP_DIR="${APP_DIR:-/opt/schedgen}"
DOCKER_HUB_USERNAME="${DOCKER_HUB_USERNAME:-}"

# Logging functions
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; echo -e "${BLUE}$1${NC}"; echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root (sudo bash server-setup.sh)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    log_error "Cannot detect OS. This script supports Ubuntu and Debian."
    exit 1
fi

log_info "Detected OS: $OS $VERSION"

# =============================================================================
# Step 1: System Update
# =============================================================================
log_step "Step 1: Updating system packages"

apt-get update
apt-get upgrade -y
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    software-properties-common \
    git \
    htop \
    jq

log_info "System packages updated"

# =============================================================================
# Step 2: Install Docker
# =============================================================================
log_step "Step 2: Installing Docker"

# Remove old versions
apt-get remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true

# Add Docker's official GPG key
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/$OS/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

# Set up the repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$OS \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker Engine
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Start and enable Docker
systemctl start docker
systemctl enable docker

# Verify installation
docker --version
docker compose version

log_info "Docker installed successfully"

# =============================================================================
# Step 3: Configure UFW Firewall
# =============================================================================
log_step "Step 3: Configuring UFW Firewall"

# Install UFW if not present
apt-get install -y ufw

# Reset to defaults
ufw --force reset

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (important: do this before enabling!)
ufw allow 22/tcp comment 'SSH'

# Allow HTTP and HTTPS for Traefik
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'

# Enable firewall
ufw --force enable

# Show status
ufw status verbose

log_info "Firewall configured - SSH, HTTP, HTTPS allowed"

# =============================================================================
# Step 4: Harden SSH
# =============================================================================
log_step "Step 4: Hardening SSH Configuration"

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

# Create hardened SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by server-setup.sh

# Disable root login
PermitRootLogin no

# Disable password authentication (require SSH keys)
PasswordAuthentication no
PubkeyAuthentication yes

# Disable empty passwords
PermitEmptyPasswords no

# Disable challenge-response authentication
ChallengeResponseAuthentication no

# Disable X11 forwarding
X11Forwarding no

# Set max authentication attempts
MaxAuthTries 3

# Set login grace time
LoginGraceTime 30

# Disable TCP forwarding (uncomment if not needed)
# AllowTcpForwarding no

# Use strong ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com

# Use strong MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Use strong key exchange algorithms
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
EOF

# Test SSH config before restarting
if sshd -t; then
    systemctl restart sshd
    log_info "SSH hardened successfully"
else
    log_error "SSH config test failed, reverting..."
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

log_warn "⚠️  IMPORTANT: Ensure you have SSH key access before disconnecting!"
log_warn "   Password authentication is now DISABLED"

# =============================================================================
# Step 5: Install and Configure fail2ban
# =============================================================================
log_step "Step 5: Installing and Configuring fail2ban"

apt-get install -y fail2ban

# Create local jail configuration
cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
# Ban duration: 1 hour
bantime = 3600

# Find time window: 10 minutes
findtime = 600

# Max retries before ban
maxretry = 5

# Action to take
banaction = ufw

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 86400
EOF

# Restart fail2ban
systemctl restart fail2ban
systemctl enable fail2ban

# Show status
fail2ban-client status

log_info "fail2ban installed and configured"

# =============================================================================
# Step 6: Create Application Directory
# =============================================================================
log_step "Step 6: Setting up application directory"

mkdir -p "$APP_DIR"
cd "$APP_DIR"

log_info "Application directory created: $APP_DIR"

# =============================================================================
# Step 7: Docker Hub Authentication
# =============================================================================
log_step "Step 7: Docker Hub Authentication"

if [ -z "$DOCKER_HUB_USERNAME" ]; then
    log_warn "DOCKER_HUB_USERNAME not set"
    read -p "Enter your Docker Hub username: " DOCKER_HUB_USERNAME
fi

if [ -n "$DOCKER_HUB_USERNAME" ]; then
    log_info "Logging into Docker Hub as $DOCKER_HUB_USERNAME..."
    docker login -u "$DOCKER_HUB_USERNAME"
    log_info "Docker Hub login successful"
else
    log_warn "Skipping Docker Hub login - you'll need to login manually"
fi

# =============================================================================
# Step 8: Clone/Setup Application Files
# =============================================================================
log_step "Step 8: Setting up application files"

# Check if docker-compose files exist
if [ ! -f "$APP_DIR/docker-compose.yml" ]; then
    log_warn "docker-compose.yml not found in $APP_DIR"
    log_info "You have two options:"
    echo "  1. Clone the repository:"
    echo "     git clone https://github.com/YOUR_USERNAME/ScheduleGenerator.git $APP_DIR"
    echo ""
    echo "  2. Copy files manually using scp or rsync"
    echo ""
    
    read -p "Clone from GitHub? (y/n): " CLONE_REPO
    if [ "$CLONE_REPO" = "y" ]; then
        read -p "Enter repository URL: " REPO_URL
        rm -rf "$APP_DIR"
        git clone "$REPO_URL" "$APP_DIR"
        cd "$APP_DIR"
    fi
fi

# =============================================================================
# Step 9: Environment Configuration
# =============================================================================
log_step "Step 9: Environment Configuration"

if [ ! -f "$APP_DIR/.env" ]; then
    if [ -f "$APP_DIR/.env.example" ]; then
        log_warn ".env file not found, copying from .env.example"
        cp "$APP_DIR/.env.example" "$APP_DIR/.env"
        log_warn "⚠️  IMPORTANT: Edit $APP_DIR/.env with production values!"
    else
        log_error ".env and .env.example not found"
        log_info "Create $APP_DIR/.env manually before starting containers"
    fi
else
    log_info ".env file exists"
fi

# Add Docker Hub username to .env if not present
if ! grep -q "DOCKER_HUB_USERNAME" "$APP_DIR/.env" 2>/dev/null; then
    echo "" >> "$APP_DIR/.env"
    echo "# Docker Hub Configuration" >> "$APP_DIR/.env"
    echo "DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME" >> "$APP_DIR/.env"
    echo "IMAGE_TAG=latest" >> "$APP_DIR/.env"
    log_info "Added Docker Hub config to .env"
fi

# =============================================================================
# Step 10: Pull Images and Start Containers
# =============================================================================
log_step "Step 10: Pulling Images and Starting Containers"

if [ -f "$APP_DIR/docker-compose.yml" ] && [ -f "$APP_DIR/.env" ]; then
    cd "$APP_DIR"
    
    # Pull images
    log_info "Pulling Docker images..."
    docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml pull
    
    # Start containers
    log_info "Starting containers..."
    docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml up -d
    
    # Wait for services
    sleep 10
    
    # Show status
    docker compose ps
    
    log_info "Containers started successfully"
else
    log_warn "Skipping container start - missing docker-compose.yml or .env"
    log_info "Run manually: cd $APP_DIR && docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml up -d"
fi

# =============================================================================
# Step 11: Create Systemd Service for Auto-Restart
# =============================================================================
log_step "Step 11: Setting up Auto-Restart Service"

cat > /etc/systemd/system/schedgen.service << EOF
[Unit]
Description=UP Schedule Generator Docker Compose Application
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml up -d
ExecStop=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

# Enable the service
systemctl daemon-reload
systemctl enable schedgen.service

log_info "Systemd service created and enabled"
log_info "Containers will auto-start on server boot"

# =============================================================================
# Step 12: Summary
# =============================================================================
log_step "Setup Complete!"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Server setup completed successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Summary:${NC}"
echo "  ✅ Docker installed and running"
echo "  ✅ UFW firewall configured (22, 80, 443 allowed)"
echo "  ✅ SSH hardened (key-only authentication)"
echo "  ✅ fail2ban installed and configured"
echo "  ✅ Application directory: $APP_DIR"
echo "  ✅ Systemd service: schedgen.service"
echo ""
echo -e "${YELLOW}⚠️  Important Next Steps:${NC}"
echo "  1. Ensure your SSH key is configured (password auth is disabled)"
echo "  2. Edit $APP_DIR/.env with production values"
echo "  3. Verify domain DNS points to this server"
echo "  4. Test application access: curl http://localhost:3000"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo "  View logs:       docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f"
echo "  Check status:    docker compose ps"
echo "  Restart:         sudo systemctl restart schedgen"
echo "  Update images:   docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.registry.yml pull && docker compose up -d"
echo ""
